'''
Environment variables defined in provider in serveless.yml
'''
import os

ALB_LOGS_DESTINATION_S3_BUCKET_NAME = os.environ.get('ALB_LOGS_DESTINATION_S3_BUCKET_NAME')
ALB_LOGS_DESTINATION_S3_BUCKET_PREFIX = os.environ.get('ALB_LOGS_DESTINATION_S3_BUCKET_PREFIX')
ATHENA_DB_NAME = os.environ.get('ATHENA_DB_NAME')
ATHENA_TABLE_NAME = os.environ.get('ATHENA_TABLE_NAME')
ATHENA_TABLE_CREATION_LOGS_S3_PATH = os.environ.get('ATHENA_TABLE_CREATION_LOGS_S3_PATH')
ATHENA_DISK_REPAIR_LOGS_S3_PATH = os.environ.get('ATHENA_DISK_REPAIR_LOGS_S3_PATH')
ATHENA_QUERY_EXECUTION_LOGS_S3_PATH = os.environ.get('ATHENA_QUERY_EXECUTION_LOGS_S3_PATH')
ATHENA_QUERY_EXECUTION_TIME_S3_KEY = os.environ.get('ATHENA_QUERY_EXECUTION_TIME_S3_KEY')
ATHENA_IS_DB_CREATED_S3_KEY = os.environ.get('ATHENA_IS_DB_CREATED_S3_KEY')
LOGZIO_URL = os.environ.get('LOGZIO_URL')
LOGZIO_TOKEN = os.environ.get('LOGZIO_TOKEN')
REGION = os.environ.get('REGION')
